# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: projects.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import service as _service
from google.protobuf import service_reflection
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from .scalapb import scalapb_pb2 as scalapb_dot_scalapb__pb2
from . import databricks_pb2 as databricks__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='projects.proto',
  package='mlflow',
  syntax='proto2',
  serialized_options=_b('\n\024org.mlflow.api.proto\220\001\001\342?\002\020\001'),
  serialized_pb=_b('\n\x0eprojects.proto\x12\x06mlflow\x1a\x15scalapb/scalapb.proto\x1a\x10\x64\x61tabricks.proto\"%\n\x13SubmittedProjectRun\x12\x0e\n\x06run_id\x18\x01 \x01(\t\".\n\x10ProjectParameter\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"\xde\x01\n\nRunProject\x12\x0f\n\x07project\x18\x01 \x01(\t\x12\x13\n\x0b\x65ntry_point\x18\x02 \x01(\t\x12\x0f\n\x07version\x18\x03 \x01(\t\x12,\n\nparameters\x18\x04 \x03(\x0b\x32\x18.mlflow.ProjectParameter\x12\x15\n\rexperiment_id\x18\x05 \x01(\t\x12\x0e\n\x06run_id\x18\x06 \x01(\t\x12\x0e\n\x06\x63onfig\x18\x07 \x01(\t\x1a\x34\n\x08Response\x12(\n\x03run\x18\x01 \x01(\x0b\x32\x1b.mlflow.SubmittedProjectRun2\xc4\x01\n\x0fProjectsService\x12\xb0\x01\n\nrunProject\x12\x12.mlflow.RunProject\x1a\x1b.mlflow.RunProject.Response\"q\xf2\x86\x19m\n)\n\x04POST\x12\x1b/mlflow/project-runs/create\x1a\x04\x08\x02\x10\x00\n1\n\x04POST\x12#/preview/mlflow/project-runs/create\x1a\x04\x08\x02\x10\x00\x10\x01*\x0bRun ProjectB\x1e\n\x14org.mlflow.api.proto\x90\x01\x01\xe2?\x02\x10\x01')
  ,
  dependencies=[scalapb_dot_scalapb__pb2.DESCRIPTOR,databricks__pb2.DESCRIPTOR,])




_SUBMITTEDPROJECTRUN = _descriptor.Descriptor(
  name='SubmittedProjectRun',
  full_name='mlflow.SubmittedProjectRun',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='run_id', full_name='mlflow.SubmittedProjectRun.run_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=104,
)


_PROJECTPARAMETER = _descriptor.Descriptor(
  name='ProjectParameter',
  full_name='mlflow.ProjectParameter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='mlflow.ProjectParameter.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='mlflow.ProjectParameter.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=106,
  serialized_end=152,
)


_RUNPROJECT_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='mlflow.RunProject.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='run', full_name='mlflow.RunProject.Response.run', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=325,
  serialized_end=377,
)

_RUNPROJECT = _descriptor.Descriptor(
  name='RunProject',
  full_name='mlflow.RunProject',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='project', full_name='mlflow.RunProject.project', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='entry_point', full_name='mlflow.RunProject.entry_point', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='version', full_name='mlflow.RunProject.version', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='parameters', full_name='mlflow.RunProject.parameters', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='experiment_id', full_name='mlflow.RunProject.experiment_id', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='run_id', full_name='mlflow.RunProject.run_id', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='config', full_name='mlflow.RunProject.config', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_RUNPROJECT_RESPONSE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=155,
  serialized_end=377,
)

_RUNPROJECT_RESPONSE.fields_by_name['run'].message_type = _SUBMITTEDPROJECTRUN
_RUNPROJECT_RESPONSE.containing_type = _RUNPROJECT
_RUNPROJECT.fields_by_name['parameters'].message_type = _PROJECTPARAMETER
DESCRIPTOR.message_types_by_name['SubmittedProjectRun'] = _SUBMITTEDPROJECTRUN
DESCRIPTOR.message_types_by_name['ProjectParameter'] = _PROJECTPARAMETER
DESCRIPTOR.message_types_by_name['RunProject'] = _RUNPROJECT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SubmittedProjectRun = _reflection.GeneratedProtocolMessageType('SubmittedProjectRun', (_message.Message,), dict(
  DESCRIPTOR = _SUBMITTEDPROJECTRUN,
  __module__ = 'projects_pb2'
  # @@protoc_insertion_point(class_scope:mlflow.SubmittedProjectRun)
  ))
_sym_db.RegisterMessage(SubmittedProjectRun)

ProjectParameter = _reflection.GeneratedProtocolMessageType('ProjectParameter', (_message.Message,), dict(
  DESCRIPTOR = _PROJECTPARAMETER,
  __module__ = 'projects_pb2'
  # @@protoc_insertion_point(class_scope:mlflow.ProjectParameter)
  ))
_sym_db.RegisterMessage(ProjectParameter)

RunProject = _reflection.GeneratedProtocolMessageType('RunProject', (_message.Message,), dict(

  Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), dict(
    DESCRIPTOR = _RUNPROJECT_RESPONSE,
    __module__ = 'projects_pb2'
    # @@protoc_insertion_point(class_scope:mlflow.RunProject.Response)
    ))
  ,
  DESCRIPTOR = _RUNPROJECT,
  __module__ = 'projects_pb2'
  # @@protoc_insertion_point(class_scope:mlflow.RunProject)
  ))
_sym_db.RegisterMessage(RunProject)
_sym_db.RegisterMessage(RunProject.Response)


DESCRIPTOR._options = None

_PROJECTSSERVICE = _descriptor.ServiceDescriptor(
  name='ProjectsService',
  full_name='mlflow.ProjectsService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=380,
  serialized_end=576,
  methods=[
  _descriptor.MethodDescriptor(
    name='runProject',
    full_name='mlflow.ProjectsService.runProject',
    index=0,
    containing_service=None,
    input_type=_RUNPROJECT,
    output_type=_RUNPROJECT_RESPONSE,
    serialized_options=_b('\362\206\031m\n)\n\004POST\022\033/mlflow/project-runs/create\032\004\010\002\020\000\n1\n\004POST\022#/preview/mlflow/project-runs/create\032\004\010\002\020\000\020\001*\013Run Project'),
  ),
])
_sym_db.RegisterServiceDescriptor(_PROJECTSSERVICE)

DESCRIPTOR.services_by_name['ProjectsService'] = _PROJECTSSERVICE

ProjectsService = service_reflection.GeneratedServiceType('ProjectsService', (_service.Service,), dict(
  DESCRIPTOR = _PROJECTSSERVICE,
  __module__ = 'projects_pb2'
  ))

ProjectsService_Stub = service_reflection.GeneratedServiceStubType('ProjectsService_Stub', (ProjectsService,), dict(
  DESCRIPTOR = _PROJECTSSERVICE,
  __module__ = 'projects_pb2'
  ))


# @@protoc_insertion_point(module_scope)
