template: "regression/v1"
target_col: "price"
steps:
  split:
    split_ratios: [0.75, 0.125, 0.125] # Train/validation/test split ratio
  evaluate:
    - metric: root_mean_squared_error
      threshold: 0.75
    - metric: mean_absolute_error
      threshold: 50
    - metric: always_one
      threshold: 0.5
metrics:
  - custom:
    name: always_one
    function: always_one_fn
    greater_is_better: True
